{
 "title": "APM of services",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "query": {
     "query": "label_values(traces_spanmetrics_calls_total,service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Red Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (client, server)(rate(traces_service_graph_request_total{server=\"$service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (client, server)(rate(traces_service_graph_request_failed_total{server=\"$service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_latency_sum{service=\"$service\"}[1m]))  by (http_target, http_method, status_code,span_name)\r\n/ \r\nsum(rate(traces_spanmetrics_latency_count{service=\"$service\"}[1m])) by (http_target, http_method, status_code,span_name)",
     "legendFormat": "{{http_target}}-{{span_name}}"
    }
   ]
  },
  {
   "title": "Traces of $service",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "filters": [
      { "id": "580770fb", "operator": "=", "scope": "span", "tag": "" }
     ],
     "limit": 20,
     "query": "{name!=\"PING\" && resource.service.name=\"$service\" && status=error}",
     "serviceMapQuery": "{service=\"nc-iam-service\"}",
     "tableType": "traces"
    }
   ]
  }
 ]
}