{
 "title": "k8s Applications overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", namespace !~\"kube-.*|cert-.*|ingress.*\"},namespace)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(kube_deployment_status_replicas_available{ namespace=\"$namespace\"},deployment)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{pod=~\"$application.*\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Service Health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{container=\"$application\", namespace=\"$namespace\", endpoint!=\"metrics\", instance!~\".*:9094\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{namespace=\"$namespace\", container=~\"$application\"}"
    }
   ]
  },
  {
   "title": "HTTP 4xx",
   "type": "stat",
   "description": "No. of 4xx requests in the range selected above",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", job=\"$application\", pod=~\"$pod\", uri!~\".*actuator.*\", status=~\"4..\"}[$__range]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HTTP 5xx",
   "type": "stat",
   "description": "No. of 5xx requests in the range selected above",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", job= \"$application\", pod=~\"$pod\", uri!~\".*actuator.*\", status=~\"5..\"}[$__range]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HTTP 4xx by Endpoint",
   "type": "timeseries",
   "description": "No. of 5xx requests in the range selected above",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{namespace=\"$namespace\", job= \"$application\", pod=~\"$pod\", uri!~\".*actuator.*\", status=~\"4..\"}[$__range])>0",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "CPU Usage by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"$application\", image!=\"\", container!=\"\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "description": "No. of requests in 5 minute range grouped by status code",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_server_requests_seconds_sum{namespace=\"$namespace\", job= \"$application\", pod=~\"$pod\", uri!~\".*actuator.*\"}[5m]) * 60)",
     "legendFormat": "HTTP {{status}} {{host}}"
    }
   ]
  },
  {
   "title": "Memory Usage by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$application\", image!=\"\", container!=\"\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "HTTP 5xx by Endpoint",
   "type": "timeseries",
   "description": "No. of 5xx requests in the range selected above",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{namespace=\"$namespace\", job= \"$application\", pod=~\"$pod\", uri!~\".*actuator.*\", status=~\"5..\"}[$__range])>0",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration(TOP 5) ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by(uri)(http_server_requests_seconds_sum{container=\"$application\"}) / sum by(uri)(http_server_requests_seconds_count{container=\"$application\"}))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  }
 ]
}