{
 "title": "Vms - Overview",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU > 70%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[5m])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[5m])))) * 100 > 70",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM > 90%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes - node_memory_MemFree_bytes) / (node_memory_MemTotal_bytes)) * 100 > 90",
     "legendFormat": "{{instance}}-{{ip_host}}"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)> 50%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by (instance)(node_load5) /  count by (instance)(count(node_cpu_seconds_total) by (cpu, instance)) * 100 > 50",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk usage > 70%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs'} * 100) / node_filesystem_size_bytes{device!~'rootfs'}) > 70 ",
     "legendFormat": "{{instance}}-{{ip_host}}-{{mountpoint}}"
    }
   ]
  },
  {
   "title": "NAT servers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "count(node_time_seconds{ip_host=~\"10.6..*|10.7..*|10.8..*|95.217.213.98|65.109.237.119|37.27.7.224|95.216.220.108|65.108.57.47|135.181.111.178|65.21.61.128|65.109.239.119|37.27.80.152|65.109.166.202|37.27.17.218|65.109.225.129|135.181.200.64|37.27.25.235|37.27.80.167|65.108.244.68|37.27.47.24|95.216.218.78|65.21.153.129|135.181.35.159|95.217.209.223|65.21.53.13|65.109.2.244|37.27.37.46|65.109.161.87\"})  by (ip_host, instance) ",
     "legendFormat": "{{instance}} - {{ip_host}}"
    }
   ]
  },
  {
   "title": "Non NAT servers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "count(node_time_seconds{ip_host!~\"10..*|95.217.213.98|65.109.237.119|37.27.7.224|95.216.220.108|65.108.57.47|135.181.111.178|65.21.61.128|65.109.239.119|37.27.80.152|65.109.166.202|37.27.17.218|65.109.225.129|135.181.200.64|37.27.25.235|37.27.80.167|65.108.244.68|37.27.47.24|95.216.218.78|65.21.153.129|135.181.35.159|95.217.209.223|65.21.53.13|65.109.2.244|37.27.37.46|65.109.161.87|95.217.37.116|95.216.101.227|116.202.170.221|78.46.41.180|116.202.170.213|116.202.114.156|5.9.31.15|49.12.126.93|135.181.177.217|138.201.21.153|144.76.45.178|136.243.156.133|95.217.37.116|144.76.218.155|95.216.101.227|116.202.170.221|116.202.170.213|116.202.228.161|116.203.255.92|135.181.177.217|135.181.154.123|88.198.216.122|65.108.61.252|162.55.175.116|78.47.219.130|23.88.114.207|49.12.39.124|95.217.187.217|49.12.107.17|49.12.46.52|49.12.39.10|49.12.9.57|5.9.31.15|88.198.163.127|65.108.106.227\"})  by (ip_host, instance)",
     "legendFormat": "{{instance}} - {{ip_host}}"
    }
   ]
  },
  {
   "title": "NAT servers - count graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(node_time_seconds{ip_host=~\"10.6..*|10.7..*|10.8..*|95.217.213.98|65.109.237.119|37.27.7.224|95.216.220.108|65.108.57.47|135.181.111.178|65.21.61.128|65.109.239.119|37.27.80.152|65.109.166.202|37.27.17.218|65.109.225.129|135.181.200.64|37.27.25.235|37.27.80.167|65.108.244.68|37.27.47.24|95.216.218.78|65.21.153.129|135.181.35.159|95.217.209.223|65.21.53.13|65.109.2.244|37.27.37.46|65.109.161.87\"})",
     "legendFormat": "{{Count(NAT_SERVERS)}}"
    }
   ]
  },
  {
   "title": "Non NAT servers - count graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(node_time_seconds{ip_host!~\"10.6..*|10.7..*|10.8..*|95.217.213.98|65.109.237.119|37.27.7.224|95.216.220.108|65.108.57.47|135.181.111.178|65.21.61.128|65.109.239.119|37.27.80.152|65.109.166.202|37.27.17.218|65.109.225.129|135.181.200.64|37.27.25.235|37.27.80.167|65.108.244.68|37.27.47.24|95.216.218.78|65.21.153.129|135.181.35.159|95.217.209.223|65.21.53.13|65.109.2.244|37.27.37.46|65.109.161.87|95.217.37.116|95.216.101.227|116.202.170.221|78.46.41.180|116.202.170.213|116.202.114.156|5.9.31.15|49.12.126.93|135.181.177.217|138.201.21.153|144.76.45.178|136.243.156.133|95.217.37.116|144.76.218.155|95.216.101.227|116.202.170.221|116.202.170.213|116.202.228.161|116.203.255.92|135.181.177.217|135.181.154.123|88.198.216.122|65.108.61.252|162.55.175.116|78.47.219.130|23.88.114.207|49.12.39.124|95.217.187.217|49.12.107.17|49.12.46.52|49.12.39.10|49.12.9.57|5.9.31.15|88.198.163.127|65.108.106.227\"})",
     "legendFormat": "{{Count(NON_NAT_SERVERS)}}"
    }
   ]
  },
  {
   "title": "NAT Servers count",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_time_seconds{ip_host=~\"10.6..*|10.7..*|10.8..*|95.217.213.98|65.109.237.119|37.27.7.224|95.216.220.108|65.108.57.47|135.181.111.178|65.21.61.128|65.109.239.119|37.27.80.152|65.109.166.202|37.27.17.218|65.109.225.129|135.181.200.64|37.27.25.235|37.27.80.167|65.108.244.68|37.27.47.24|95.216.218.78|65.21.153.129|135.181.35.159|95.217.209.223|65.21.53.13|65.109.2.244|37.27.37.46|65.109.161.87\"}) "
    }
   ]
  },
  {
   "title": "Non NAT Servers count",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_time_seconds{ip_host!~\"10.6..*|10.7..*|10.8..*|95.217.213.98|65.109.237.119|37.27.7.224|95.216.220.108|65.108.57.47|135.181.111.178|65.21.61.128|65.109.239.119|37.27.80.152|65.109.166.202|37.27.17.218|65.109.225.129|135.181.200.64|37.27.25.235|37.27.80.167|65.108.244.68|37.27.47.24|95.216.218.78|65.21.153.129|135.181.35.159|95.217.209.223|65.21.53.13|65.109.2.244|37.27.37.46|65.109.161.87|95.217.37.116|95.216.101.227|116.202.170.221|78.46.41.180|116.202.170.213|116.202.114.156|5.9.31.15|49.12.126.93|135.181.177.217|138.201.21.153|144.76.45.178|136.243.156.133|95.217.37.116|144.76.218.155|95.216.101.227|116.202.228.161|116.203.255.92|135.181.177.217|135.181.154.123|88.198.216.122|65.108.61.252|162.55.175.116|78.47.219.130|23.88.114.207|49.12.39.124|95.217.187.217|49.12.107.17|49.12.46.52|49.12.39.10|49.12.9.57|5.9.31.15|88.198.163.127|65.108.106.227|116.202.230.220|135.181.177.217\"}) "
    }
   ]
  },
  {
   "title": "Mysql count",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mysql_global_status_uptime{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database server count",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_time_seconds{ip_host=~\"95.217.37.116|95.216.101.227|116.202.170.221|78.46.41.180|116.202.170.213|116.202.114.156|5.9.31.15|49.12.126.93|135.181.177.217|138.201.21.153|144.76.45.178|136.243.156.133|144.76.218.155|116.202.228.161|116.203.255.92|135.181.154.123|88.198.216.122|65.108.61.252|162.55.175.116|78.47.219.130|23.88.114.207|49.12.39.124|95.217.187.217|49.12.107.17|49.12.46.52|49.12.39.10|49.12.9.57|5.9.31.15|88.198.163.127|65.108.106.227|188.40.80.228|138.201.49.235|94.130.223.182|88.99.214.29|178.63.92.22|188.40.102.141|178.63.60.251|116.202.230.220|65.108.106.228|144.76.45.213|65.21.253.185|95.217.21.172|162.55.42.205|159.69.191.36|49.12.107.17|88.99.214.29|142.132.185.223\"}) "
    }
   ]
  },
  {
   "title": "Database server - node exporter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "count(node_time_seconds{ip_host=~\"95.217.37.116|95.216.101.227|116.202.170.221|78.46.41.180|116.202.170.213|116.202.114.156|5.9.31.15|49.12.126.93|135.181.177.217|138.201.21.153|144.76.45.178|136.243.156.133|144.76.218.155|116.202.228.161|116.203.255.92|135.181.154.123|88.198.216.122|65.108.61.252|162.55.175.116|78.47.219.130|23.88.114.207|49.12.39.124|95.217.187.217|49.12.107.17|49.12.46.52|49.12.39.10|49.12.9.57|5.9.31.15|88.198.163.127|65.108.106.227|188.40.80.228|138.201.49.235|94.130.223.182|88.99.214.29|178.63.92.22|188.40.102.141|178.63.60.251|116.202.230.220|65.108.106.228|144.76.45.213|65.21.253.185|95.217.21.172|162.55.42.205|159.69.191.36|49.12.107.17|88.99.214.29|142.132.185.223\"})  by (ip_host, instance)",
     "legendFormat": "{{instance}} - {{ip_host}}"
    }
   ]
  },
  {
   "title": "Mysql servers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    { "expr": "mysql_global_status_uptime{}", "legendFormat": "{{job}}" }
   ]
  }
 ]
}