apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-web-app
  labels:
    app: basic-web-app
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: basic-web-app
  template:
    metadata:
      labels:
        app: basic-web-app
        tier: frontend
    spec:
      containers:
      - name: web-app
        image: spicybiryaniwala.shop/web-app:v1.0.0
        ports:
        - containerPort: 8080
          name: http
        
        env:
        - name: APP_ENV
          value: "production"
        - name: LOG_LEVEL
          value: "info"
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: basic-web-app-service
  labels:
    app: basic-web-app
spec:
  selector:
    app: basic-web-app
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP