{
 "title": "Databases - Overview",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Mysql Uptime (In Months)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mysql_global_status_uptime / 2592000\n",
     "legendFormat": "{{job}}  \"{{instance}}\""
    }
   ]
  },
  {
   "title": "Mysql Down count",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(mysql_up != 1)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mysql Downtime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "targets": [
    { "expr": "mysql_up != 1", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Database server count",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_time_seconds{ip_host=~\"116.202.114.156|116.202.170.213|116.202.170.221|116.202.228.161|116.202.230.220|135.181.154.123|135.181.177.217|136.243.156.133|138.201.21.153|138.201.49.235|144.76.218.155|144.76.45.178|144.76.45.213|159.69.191.36|162.55.175.116|178.63.60.251|178.63.92.22|188.40.102.141|188.40.80.228|23.88.114.207|49.12.107.17|49.12.126.93|49.12.39.10|49.12.39.124|49.12.46.52|49.12.9.57|5.9.31.15|65.108.106.228|65.108.61.252|78.46.41.180|78.47.219.130|88.198.216.122|88.99.214.29|94.130.223.182|95.216.101.227|95.217.187.217|95.217.37.116|95.217.21.172|88.198.163.127|162.55.42.205|142.132.185.223|65.108.106.227|116.203.255.92|65.21.253.185|65.21.215.145\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max connection",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "max_over_time(mysql_global_status_threads_connected[5m])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Io Max Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Full",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 21 },
   "targets": [
    {
     "expr": "max(100 - ((node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes)) by (instance) > 90",
     "legendFormat": "{{instance}}-{{ip_host}}-{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Replication delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "mysql_slave_status_seconds_behind_master",
     "legendFormat": "{{job}} \"{{master_host}}\""
    }
   ]
  },
  {
   "title": "Disk usage > 80%",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs'} * 100) / node_filesystem_size_bytes{device!~'rootfs'}) > 80",
     "legendFormat": "{{instance}}-{{ip_host}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "100 - (\n  avg by (instance, ip_host) (\n    rate(node_cpu_seconds_total{mode=\"idle\"}[5m])\n  ) * 100\n)\n",
     "legendFormat": "{{instance}}-{{ip_host}}"
    }
   ]
  },
  {
   "title": "Slave IO Thread Not Running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running == 0",
     "legendFormat": "{{job}} \"{{master_host}}\""
    }
   ]
  },
  {
   "title": "Slave SQL Thread Not Running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_sql_running == 0\n",
     "legendFormat": "{{job}} \"{{master_host}}\""
    }
   ]
  },
  {
   "title": "Slave SQL Replication Lag:Seconds Behind Master",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "(mysql_slave_status_seconds_behind_master > 60) and on(instance) (predict_linear(mysql_slave_status_seconds_behind_master[5m], 60 * 2) > 0)\n",
     "legendFormat": "{{job}} \"{{master_host}}\" {{instance}}"
    }
   ]
  }
 ]
}