{
 "title": "Database Backup Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Backup Success Rate ",
   "type": "stat",
   "description": "Backup Present in storage box ",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(db) (mysql_backup_success)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Backup Size in S3",
   "type": "bargauge",
   "description": "Size of last pushed backup in S3",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(db) (mysql_backup_size_s3_bytes) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Backup Size Local",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(db) (mysql_backup_size_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "S3 Bucket Size ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(storage_location) (s3_bucket_size_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Stored Backup in S3",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(db) (s3_last_backup_time) * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}