{
 "title": "PgBouncer-postgres",
 "description": "A visual representation of Prometheus metrics collected from PgBouncer servers.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(pgbouncer_up, instance)"
   },
   {
    "name": "port",
    "query": "label_values(pgbouncer_up, instance)"
   },
   {
    "name": "db",
    "label": "Db",
    "query": "label_values(pgbouncer_databases_current_connections,database)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(pgbouncer_up, service)"
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "pgbouncer status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pgbouncer_up{job=~\"pgbouncer-pgbouncer\"}"
    },
    {}
   ]
  },
  {
   "title": "Stats queries total $db",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc( sum (pgbouncer_stats_queries_pooled_total{database=~\"$db\"} ) )"
    }
   ]
  },
  {
   "title": "Database pool size.",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (pgbouncer_databases_pool_size{database=~\"$db\"})",
     "legendFormat": "{{database}},{{service}}"
    }
   ]
  },
  {
   "title": "Client active connections $db",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (pgbouncer_pools_client_active_connections{database=~\"$db\"})"
    }
   ]
  },
  {
   "title": "Clients Active",
   "type": "graph",
   "description": "Server connections that are linked to a client.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pgbouncer_pools_client_active_connections{job=\"pgbouncer-pgbouncer\"})",
     "legendFormat": "Active clients"
    }
   ]
  },
  {
   "title": "Total Query Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sort_desc(sum by(database) (rate(pgbouncer_stats_queries_duration_seconds_total{job=\"pgbouncer-pgbouncer\"}[1m])))",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Total Transaction",
   "type": "timeseries",
   "description": "Total number of SQL transactions pooled by pgbouncer",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer_stats_server_in_transaction_seconds_total{job=\"pgbouncer-pgbouncer\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Stats queries",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc( sum ( rate(pgbouncer_stats_queries_duration_seconds_total{database=~\"$db\"}[30m]) ) )",
     "legendFormat": "Duration microseconds"
    },
    {
     "expr": "sort_desc( sum ( rate(pgbouncer_pools_client_maxwait_seconds{database=~\"$db\"}[30m]) ) ) ",
     "legendFormat": "Waiting duration microseconds"
    }
   ]
  },
  {
   "title": "Transactions stats",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc( sum ( rate(pgbouncer_stats_server_in_transaction_seconds{database=~\"$db\"}[30m]) ) )  ",
     "legendFormat": "Transactions duration microseconds"
    },
    {
     "expr": "sort_desc( sum ( rate(pgbouncer_stats_sql_transactions_pooled_total{database=~\"$db\"}[30m]) ) )",
     "legendFormat": "Transactions total"
    }
   ]
  },
  {
   "title": "Pools Connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pgbouncer_pools_client_active_connections{database=~\"$db\"}",
     "legendFormat": "Client active connections "
    },
    {
     "expr": "pgbouncer_pools_client_waiting_connections{database=~\"$db\"}",
     "legendFormat": "Client waiting connections"
    },
    {
     "expr": "pgbouncer_pools_server_active_connections{database=~\"$db\"}",
     "legendFormat": "Server active connections"
    },
    {
     "expr": "pgbouncer_pools_server_idle_connections{database=~\"$db\"}",
     "legendFormat": "Server idle connections"
    },
    {
     "expr": "pgbouncer_pools_server_used_connections{database=~\"$db\"}",
     "legendFormat": "Server used connections"
    },
    {
     "expr": "pgbouncer_pools_server_testing_connections{database=~\"$db\"}",
     "legendFormat": "Server testing connections"
    },
    {
     "expr": "pgbouncer_pools_server_login_connections{database=~\"$db\"}",
     "legendFormat": "Server login connections"
    },
    {
     "expr": "pgbouncer_databases_current_connections{database=~\"$db\"}",
     "legendFormat": "Database current connections"
    }
   ]
  },
  {
   "title": "Total of incoming / outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc( sum ( rate(pgbouncer_stats_received_bytes_total{database=~\"$db\"}[30m])*8 ) )",
     "legendFormat": "Received bytes total"
    },
    {
     "expr": "sort_desc( sum ( rate(pgbouncer_stats_sent_bytes_total{database=~\"$db\"}[30m])*8 ) )",
     "legendFormat": "Sent bytes total"
    }
   ]
  },
  {
   "title": "Total Query Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sort_desc( sum ( rate(pgbouncer_stats_queries_duration_seconds_total{database=\"$db\"}[30m]) ) )",
     "legendFormat": "{{database}}"
    }
   ]
  }
 ]
}