# Advanced Pod with Multiple Containers, Volumes, and Security
apiVersion: v1
kind: Pod
metadata:
  name: advanced-pod
  namespace: default
  labels:
    app: advanced-app
    tier: backend
  annotations:
    description: "Advanced pod with multiple containers and volumes"
spec:
  serviceAccountName: default
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  
  # Init Container
  initContainers:
  - name: init-container
    image: busybox:latest
    command: ['sh', '-c', 'echo "Initializing..." && sleep 10']
  
  containers:
  # Main Application Container
  - name: app-container
    image: nginx:alpine
    ports:
    - containerPort: 80
      name: http
    env:
    - name: ENV_VAR
      value: "production"
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
    - name: config-volume
      mountPath: /etc/nginx/conf.d
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
  
  # Sidecar Container
  - name: sidecar-container
    image: busybox:latest
    command: ['sh', '-c', 'while true; do echo "$(date): Sidecar running" >> /shared/sidecar.log; sleep 30; done']
    volumeMounts:
    - name: shared-data
      mountPath: /shared
    resources:
      requests:
        memory: "32Mi"
        cpu: "25m"
      limits:
        memory: "64Mi"
        cpu: "50m"
  
  volumes:
  - name: shared-data
    emptyDir: {}
  - name: config-volume
    configMap:
      name: nginx-config
  
  # Node Selection
  nodeSelector:
    kubernetes.io/os: linux
  
  # Tolerations
  tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
  
  # Affinity
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
  
  restartPolicy: Always
  terminationGracePeriodSeconds: 30