# Pod Lifecycle Hooks and Phases
apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-pod
  namespace: default
  labels:
    app: lifecycle-demo
spec:
  containers:
  - name: lifecycle-container
    image: nginx:alpine
    ports:
    - containerPort: 80
    
    # Lifecycle Hooks
    lifecycle:
      postStart:
        exec:
          command:
          - /bin/sh
          - -c
          - |
            echo "Pod started at $(date)" > /tmp/lifecycle.log
            echo "PostStart hook executed" >> /tmp/lifecycle.log
      preStop:
        exec:
          command:
          - /bin/sh
          - -c
          - |
            echo "Pod stopping at $(date)" >> /tmp/lifecycle.log
            echo "PreStop hook executed" >> /tmp/lifecycle.log
            # Graceful shutdown
            nginx -s quit
    
    # Health Checks
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 3
    
    startupProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 30
    
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
  
  restartPolicy: Always
  terminationGracePeriodSeconds: 30

---
# Pod Phases Example
# Pending: Pod accepted but not scheduled
# Running: Pod bound to node and containers created
# Succeeded: All containers terminated successfully
# Failed: All containers terminated, at least one failed
# Unknown: Pod state cannot be determined