{
 "title": "Applications",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{namespace=\"platform\"},namespace)"
    }
   },
   { "name": "application", "label": "Application", "query": "nc-risk-service" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service Health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{service=\"$application\", namespace=\"$namespace\", endpoint!=\"metrics\", instance!~\".*:9094\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{namespace=\"$namespace\", service=~\"$application\"}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$application\", uri!=\"/actuator/prometheus\"})"
    }
   ]
  },
  {
   "title": "Requests (Period)",
   "type": "stat",
   "description": "No. of requests in interval",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=~\"$application\", uri!~\".*actuator.*\"}[$__range]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HTTP 2xx",
   "type": "stat",
   "description": "No. of 2xx requests in the range selected above",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=~\"$application\", uri!~\".*actuator.*\", status=~\"2..\"}[$__range]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HTTP 4xx",
   "type": "stat",
   "description": "No. of 4xx requests in the range selected above",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$application\",uri!~\".*actuator.*\", status=~\"4..\"}[$__range]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HTTP 5xx",
   "type": "stat",
   "description": "No. of 5xx requests in the range selected above",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", service= \"$application\", uri!~\".*actuator.*\", status=~\"5..\"}[$__range]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$application\", outcome=~\"SERVER_ERROR|CLIENT_ERROR\"})"
    }
   ]
  },
  { "title": "Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "LATENCY",
   "type": "timeseries",
   "description": "99th, 95th and 50th percentiles",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{namespace=\"$namespace\",service=~\"$application\"}[5m])) by (le)) * 1 ",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{namespace=\"$namespace\",service=~\"$application\"}[5m])) by (le)) * 1 ",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{namespace=\"$namespace\",service=~\"$application\"}[5m])) by (le)) * 1 ",
     "legendFormat": "50th Percentile"
    }
   ]
  },
  {
   "title": "TRAFFIC",
   "type": "timeseries",
   "description": "Method & Status",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (uri, status) (rate(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$application\", uri!~\"/actuator/.*\"}[$__range])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ERRORS",
   "type": "timeseries",
   "description": "4xx & 5xx",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (status,uri) (rate(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$application\", status=~\"4..\"}[$__range])) >0",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (status,uri) (rate(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$application\",status=~\"5..\"}[$__range])) >0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SATURATION",
   "type": "timeseries",
   "description": "Node CPU ",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  { "title": "Additional Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Requests Average Duration(TOP 5) ",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by(uri)(http_server_requests_seconds_sum{service=\"$application\"}) / sum by(uri)(http_server_requests_seconds_count{service=\"$application\"}))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "HTTP 5xx by Endpoint",
   "type": "timeseries",
   "description": "No. of 5xx requests in the range selected above",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 29 },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{namespace=\"$namespace\", service= \"$application\", status=~\"5..\"}[$__range])>0",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "HTTP 4xx by Endpoint",
   "type": "timeseries",
   "description": "No. of 5xx requests in the range selected above",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 29 },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$application\", status=~\"4..\"}[$__range])>0",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "System Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage by container",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"$application\", image!=\"\", container!=\"\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Memory Usage by container",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$application\", image!=\"\", container!=\"\"}) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Total pod CPU Requests usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"$application\", image!=\"\"}[$__rate_interval])) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"$application\", unit=\"core\"})",
       "legendFormat": "Requests"
      }
     ]
    },
    {
     "title": "Total pod CPU Limits usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 3, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"$application\", image!=\"\"}[$__rate_interval])) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$application\", unit=\"core\"})",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Total pod RAM Requests usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 6, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$application\", image!=\"\"}) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"$application\", unit=\"byte\"})",
       "legendFormat": "Requests"
      }
     ]
    },
    {
     "title": "Total pod RAM Limits usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 9, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$application\", image!=\"\"}) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$application\", unit=\"byte\"}) ",
       "legendFormat": "Limits"
      }
     ]
    }
   ]
  }
 ]
}