# NodePort Service Examples

---
# Basic NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: web-nodeport
  labels:
    app: web-app
    tier: frontend
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30080
    protocol: TCP

---
# Multi-Port NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: api-nodeport
  labels:
    app: api-server
spec:
  type: NodePort
  selector:
    app: api-server
  ports:
  - name: api
    port: 8080
    targetPort: 8080
    nodePort: 30080
  - name: metrics
    port: 9090
    targetPort: 9090
    nodePort: 30090

---
# NodePort with Custom Configuration
apiVersion: v1
kind: Service
metadata:
  name: custom-nodeport
  labels:
    app: custom-app
spec:
  type: NodePort
  selector:
    app: custom-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30100
  externalTrafficPolicy: Local
  sessionAffinity: ClientIP