{
 "title": "CoreDNS",
 "tags": [ "coredns-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(coredns_build_info{job=~\"integrations/coredns\"}, cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(coredns_build_info{job=~\"integrations/coredns\", cluster=\"$cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(up{job=~\"integrations/coredns\", cluster=\"$cluster\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Panics",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(coredns_panics_total{job=~\"integrations/coredns\", cluster=\"$cluster\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_responses_total{job=~\"integrations/coredns\", cluster=\"$cluster\",instance=~\"$instance\"}[$__rate_interval])) by (rcode)",
     "legendFormat": "{{rcode}}"
    },
    {
     "expr": "sum(rate(coredns_forward_responses_total{job=~\"integrations/coredns\", cluster=\"$cluster\",instance=~\"$instance\"}[$__rate_interval])) by (rcode)",
     "legendFormat": "forward {{rcode}}"
    }
   ]
  },
  {
   "title": "Request duration 99th quantile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket{job=~\"integrations/coredns\", cluster=\"$cluster\",instance=~\"$instance\"}[$__rate_interval])) by (server, zone, le))",
     "legendFormat": "{{server}} {{zone}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_forward_request_duration_seconds_bucket{job=~\"integrations/coredns\", cluster=\"$cluster\",instance=~\"$instance\"}[$__rate_interval])) by (to, le))",
     "legendFormat": "forward {{to}}"
    }
   ]
  },
  {
   "title": "Requests (by qtype)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{job=~\"integrations/coredns\", cluster=\"$cluster\",instance=~\"$instance\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Requests (by zone)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{job=~\"integrations/coredns\", cluster=\"$cluster\",instance=~\"$instance\"}[$__rate_interval])) by (zone)",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "Forward Requests (by to)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_requests_total{job=~\"integrations/coredns\", cluster=\"$cluster\",instance=~\"$instance\"}[$__rate_interval])) by (to)",
     "legendFormat": "{{to}}"
    }
   ]
  },
  {
   "title": "Cached",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(coredns_cache_hits_total{job=~\"integrations/coredns\", cluster=\"$cluster\",instance=~\"$instance\"}) / (sum(coredns_cache_misses_total{job=~\"integrations/coredns\", cluster=\"$cluster\",instance=~\"$instance\"}) + sum(coredns_cache_hits_total{job=~\"integrations/coredns\", cluster=\"$cluster\",instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Cache hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{job=~\"integrations/coredns\", cluster=\"$cluster\",instance=~\"$instance\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(rate(coredns_cache_misses_total{job=~\"integrations/coredns\", cluster=\"$cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(coredns_cache_entries{job=~\"integrations/coredns\", cluster=\"$cluster\",instance=~\"$instance\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Plugins Enabled",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "count(sum(coredns_plugin_enabled{job=~\"integrations/coredns\", cluster=\"$cluster\",instance=~\"$instance\"}) by (name))"
    }
   ]
  },
  {
   "title": "Request size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_size_bytes_bucket{job=~\"integrations/coredns\", cluster=\"$cluster\",instance=~\"$instance\"}[$__rate_interval])) by (server, zone, proto, le))",
     "legendFormat": "99th {{server}} {{zone}} {{proto}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_size_bytes_bucket{job=~\"integrations/coredns\", cluster=\"$cluster\",instance=~\"$instance\"}[$__rate_interval])) by (server, zone, proto, le))",
     "legendFormat": "50th {{server}} {{zone}} {{proto}}"
    }
   ]
  },
  {
   "title": "Response size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_response_size_bytes_bucket{job=~\"integrations/coredns\", cluster=\"$cluster\",instance=~\"$instance\"}[$__rate_interval])) by (server, zone, proto, le))",
     "legendFormat": "99th {{server}} {{zone}} {{proto}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_response_size_bytes_bucket{job=~\"integrations/coredns\", cluster=\"$cluster\",instance=~\"$instance\"}[$__rate_interval])) by (server, zone, proto, le))",
     "legendFormat": "50th {{server}} {{zone}} {{proto}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"integrations/coredns\", cluster=\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"integrations/coredns\", cluster=\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"integrations/coredns\", cluster=\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}