# Basic ReplicaSet
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  namespace: default
  labels:
    app: nginx
    tier: frontend
spec:
  # Number of desired replicas
  replicas: 3
  
  # Selector to match pods
  selector:
    matchLabels:
      app: nginx
      version: v1
  
  # Pod template
  template:
    metadata:
      labels:
        app: nginx
        version: v1
        tier: frontend
    spec:
      containers:
      - name: nginx-container
        image: nginx:alpine
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: NGINX_PORT
          value: "80"
      restartPolicy: Always

---
# ReplicaSet with Advanced Configuration
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-app-replicaset
  namespace: default
  labels:
    app: web-app
    environment: production
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-app
    matchExpressions:
    - key: version
      operator: In
      values: ["v1", "v2"]
  template:
    metadata:
      labels:
        app: web-app
        version: v1
        environment: production
    spec:
      containers:
      - name: web-container
        image: nginx:alpine
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      # Node selection
      nodeSelector:
        kubernetes.io/os: linux
      # Affinity rules
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values: ["web-app"]
              topologyKey: kubernetes.io/hostname