{
 "title": "MySQL logs",
 "tags": [ "mysql-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(mysql_up, cluster)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values({job=\"integrations/mysql\"}, cluster)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values({job=\"integrations/mysql\",cluster=~\"$cluster\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({job=\"integrations/mysql\",cluster=~\"$cluster\",job=~\"$job\"}, instance)"
   },
   {
    "name": "level",
    "label": "Level",
    "query": "label_values({job=\"integrations/mysql\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}, level)"
   },
   {
    "name": "subsystem",
    "label": "Subsystem",
    "query": "label_values({job=\"integrations/mysql\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",level=~\"$level\"}, subsystem)"
   },
   {
    "name": "err_code",
    "label": "Err_code",
    "query": "label_values({job=\"integrations/mysql\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\",level=~\"$level\",subsystem=~\"$subsystem\"}, err_code)"
   },
   { "name": "regex_search", "label": "Regex search" }
  ]
 },
 "panels": [
  { "title": "Integration Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logs",
   "type": "stat",
   "description": "Shows if logs are being received for the selected time range.",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"integrations/mysql\"}[5m]))\n"
    }
   ]
  },
  {
   "title": "Latest logs received",
   "type": "stat",
   "description": "Shows the timestamp of the latest logs received for this integration in the last 24 hours.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"integrations/mysql\"}[5m]))\n"
    }
   ]
  },
  {
   "title": "Integration version",
   "type": "stat",
   "description": "Shows the installed version of this integration.",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Logs volume",
   "type": "timeseries",
   "description": "Logs volume grouped by \"level\" label.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({job=\"integrations/mysql\",cluster=~\"$cluster\",cluster=~\"$cluster\", job=~\"$job\",instance=~\"$instance\",level=~\"$level\",subsystem=~\"$subsystem\",err_code=~\"$err_code\"}\n|~ \"$regex_search\"\n\n[$__interval]))\n",
     "legendFormat": "{{ level }}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{job=\"integrations/mysql\",cluster=~\"$cluster\",cluster=~\"$cluster\", job=~\"$job\",instance=~\"$instance\",level=~\"$level\",subsystem=~\"$subsystem\",err_code=~\"$err_code\"} \n|~ \"$regex_search\"\n\n\n"
    }
   ]
  }
 ]
}