apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-with-sidecar
  labels:
    app: web-app-sidecar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app-sidecar
  template:
    metadata:
      labels:
        app: web-app-sidecar
    spec:
      containers:
      # Main application container
      - name: web-app
        image: spicybiryaniwala.shop/web-app:v1.0.0
        ports:
        - containerPort: 8080
        
        volumeMounts:
        - name: shared-logs
          mountPath: /var/log/app
        - name: shared-data
          mountPath: /shared
        
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      
      # Sidecar: Log collector
      - name: log-collector
        image: fluentd:v1.14-debian
        env:
        - name: FLUENTD_CONF
          value: "fluent.conf"
        
        volumeMounts:
        - name: shared-logs
          mountPath: /var/log/app
        - name: fluentd-config
          mountPath: /fluentd/etc
        
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      
      # Sidecar: Monitoring agent
      - name: monitoring-agent
        image: prom/node-exporter:latest
        ports:
        - containerPort: 9100
          name: metrics
        
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
        
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      
      # Sidecar: Nginx proxy
      - name: nginx-proxy
        image: nginx:1.21-alpine
        ports:
        - containerPort: 80
        
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      
      volumes:
      - name: shared-logs
        emptyDir: {}
      - name: shared-data
        emptyDir: {}
      - name: fluentd-config
        configMap:
          name: fluentd-config
      - name: nginx-config
        configMap:
          name: nginx-proxy-config
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/app/*.log
      pos_file /var/log/fluentd-app.log.pos
      tag app.logs
      format json
    </source>
    
    <match app.logs>
      @type elasticsearch
      host elasticsearch.logging.svc.cluster.local
      port 9200
      index_name app-logs
    </match>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy-config
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        upstream app {
            server localhost:8080;
        }
        
        server {
            listen 80;
            
            location / {
                proxy_pass http://app;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
            
            location /metrics {
                proxy_pass http://localhost:9100/metrics;
            }
        }
    }