{
 "title": "Application Health Dashboard (VM)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up,cluster)" } },
   { "name": "application", "label": "Application", "query": { "query": "label_values(job)" } },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{cluster=\"$cluster\", job=\"$application\"},host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service Health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (host, job) (increase(http_server_requests_seconds_count{job=\"$application\", host=~\"$host\", uri=~\".*actuator/prometheus\", status=\"200\"}[5m]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Requests (Period)",
   "type": "stat",
   "description": "No. of requests in interval",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (increase(http_server_requests_seconds_count{job= \"$application\", host=~\"$host\", uri!~\".*actuator/prometheus\"}[$__range]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HTTP 2xx",
   "type": "stat",
   "description": "No. of 2xx requests in the range selected above",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (increase(http_server_requests_seconds_count{job= \"$application\",host=~\"$host\", uri!~\".*actuator/prometheus\", status=~\"2..\"}[$__range]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HTTP 4xx",
   "type": "stat",
   "description": "No. of 4xx requests in the range selected above",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (increase(http_server_requests_seconds_count{job=\"$application\", host=~\"$host\", uri!~\".*actuator/prometheus\", status=~\"4..\"}[$__range]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HTTP 5xx",
   "type": "stat",
   "description": "No. of 5xx requests in the range selected above",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (increase(http_server_requests_seconds_count{job= \"$application\", host=~\"$host\", uri!~\".*actuator/prometheus\", status=~\"5..\"}[$__range]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "HTTP Requests By Host",
   "type": "timeseries",
   "description": "No. of requests in 5 minute range",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (host) (rate(http_server_requests_seconds_sum{job= \"$application\", host=~\"$host\", uri!~\".*actuator/prometheus\"}[5m]) * 60)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "description": "No. of requests in 5 minute range grouped by status code",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_server_requests_seconds_sum{job= \"$application\", host=~\"$host\", uri!~\".*actuator/prometheus\"}[5m]) * 60)",
     "legendFormat": "HTTP {{status}} {{host}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "99th, 95th and 50th percentiles",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_bucket{job=~\"$application-exemplar\", host=~\"$host\"}[5m])) by (le)) * 1 ",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{job=~\"$application-exemplar\",host=~\"$host\"}[5m])) by (le)) * 1 ",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_bucket{job=~\"$application-exemplar\",host=~\"$host\"}[5m])) by (le)) * 1 ",
     "legendFormat": "50th Percentile"
    }
   ]
  },
  {
   "title": "Top 5xx URI",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5 ,sum by(uri)(rate(http_server_requests_seconds_count{job=\"$application\",host =~ \"$host\",status =\"500\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Container restart Timeline",
   "type": "timeseries",
   "description": "give the timeline of container restart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count_over_time({container=\"$application\"} |= `Started Application` [5m])",
     "resolution": 1
    }
   ]
  }
 ]
}