{
 "title": "Autosweep Response",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Exceptions-{realm_id}/{userId}/autoSweep/settlementDetails",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (exception) (increase(http_server_requests_seconds_count{uri=~\"/{realm_id}/{userId}/autoSweep/settlementDetails\",status=~\"2.*\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (exception) (increase(http_server_requests_seconds_count{uri=~\"/{realm_id}/{userId}/autoSweep/settlementDetails\",status=~\"4.*\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (exception) (increase(http_server_requests_seconds_count{uri=~\"/{realm_id}/{userId}/autoSweep/settlementDetails\",status=~\"5.*\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exceptions-{realmId}/{userId}/payments/withdraw",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (exception) (increase(http_server_requests_seconds_count{uri=~\"/{realmId}/{userId}/payments/withdraw\",status=~\"2.*\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (exception) (increase(http_server_requests_seconds_count{uri=~\"/{realmId}/{userId}/payments/withdraw\",status=~\"4.*\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (exception) (increase(http_server_requests_seconds_count{uri=~\"/{realmId}/{userId}/payments/withdraw\",status=~\"5.*\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Api counts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (uri) (increase(http_server_requests_seconds_count{uri=~\"/{realm_id}/{userId}/autoSweep/settlementDetails|/{realmId}/{userId}/payments/withdraw\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Api counts",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (uri) (increase(http_server_requests_seconds_count{uri=~\"/{realm_id}/{userId}/autoSweep/settlementDetails|/{realmId}/{userId}/payments/withdraw\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "2xx rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=~\"van-service|payment-service\",instance=~\".*\",status=~\"2..\",uri=~\"/{realm_id}/{userId}/autoSweep/settlementDetails|/{realmId}/{userId}/payments/withdraw\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=~\"van-service|payment-service\",instance=~\".*\",status=~\"4..\",uri=~\"/{realm_id}/{userId}/autoSweep/settlementDetails|/{realmId}/{userId}/payments/withdraw\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=~\"van-service|payment-service\",instance=~\".*\",status=~\"5..\",uri=~\"/{realm_id}/{userId}/autoSweep/settlementDetails|/{realmId}/{userId}/payments/withdraw\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}