{
 "title": "Custom Error Metric",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", namespace !~\"kube-.*|cert-.*|ingress.*\"},namespace)"
    }
   },
   {
    "name": "application",
    "label": "application",
    "query": {
     "query": "label_values(kube_deployment_status_replicas_available{ namespace=\"$namespace\"},deployment)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{pod=~\"$application.*\"},pod)"
    }
   },
   { "name": "log_data_source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "LSP V2 Metrics based latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "P99 Service Latency by api",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, http_route) (rate(http_server_duration_bucket{container=\"$application\"}[1m])))",
     "legendFormat": "{{http_route}}-99"
    }
   ]
  },
  {
   "title": "P95 Service Latency by api",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, http_route) (rate(http_server_duration_bucket{container=\"$application\"}[1m])))",
     "legendFormat": "{{http_route}}-95"
    }
   ]
  },
  {
   "title": "P50 Service Latency by api",
   "type": "timeseries",
   "description": "50th percentiles",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le, http_route) (rate(http_server_duration_bucket{container=\"$application\"}[1m])))",
     "legendFormat": "{{http_route}}-50"
    }
   ]
  },
  {
   "title": "Requests Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(http_method, http_route) (rate(http_server_duration_count{container=\"$application\"}[1m]))",
     "legendFormat": "{{http_method}}:{{http_route}}"
    }
   ]
  },
  {
   "title": "Average Api time",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(http_route, http_method)(http_server_duration_sum{container=\"$application\", http_route!~\".*api-docs.*||.*actuator.*\"}) /sum by(http_route, http_method)(http_server_duration_count{container=\"$application\", http_route!~\".*api-docs.*||.*actuator.*\"})",
     "legendFormat": "{{http_method}} : {{http_route}}"
    }
   ]
  },
  { "title": "Error Metrics LSP-v2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Critical Severity Error Rate",
   "type": "stat",
   "description": "No. of critical-severity errors in the range selected above",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (increase(critical_error_count_total{namespace=\"$namespace\", job=\"$application\", pod=~\"$pod\"}[$__range]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Severity High Error Rate",
   "type": "stat",
   "description": "No. of high-severity errors in range selected above",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (increase(severe_error_count_total{namespace=\"$namespace\", job=\"$application\", pod=~\"$pod\"}[$__range]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Severity Medium Error Rate",
   "type": "stat",
   "description": "No. of medium-severity errors in range selected above",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (increase(moderate_error_count_total{namespace=\"$namespace\", job=\"$application\", pod=~\"$pod\"}[$__range]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Severity Low Error Rate",
   "type": "stat",
   "description": "No. of low-severity errors in range selected above",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (increase(low_error_count_total{namespace=\"$namespace\", job=\"$application\", pod=~\"$pod\"}[1h]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Client Request Latency",
   "type": "timeseries",
   "description": "99th, 95th and 50th percentiles",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, http_url) (rate(http_client_requests_bucket{container=\"$application\"}[$__range])))",
     "legendFormat": "{{http_url}}-99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, http_url) (rate(http_client_requests_bucket{container=\"$application\"}[$__range])))",
     "legendFormat": "{{http_url}}-95"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le, http_url) (rate(http_client_requests_bucket{container=\"$application\"}[$__range])))",
     "legendFormat": "{{http_url}}-50"
    }
   ]
  },
  {
   "title": "Slowest Client Apis",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20, sum by(http_url, http_method) (http_client_requests_sum{container=\"$application\"})) / sum by(http_url, http_method) (http_client_requests_count{container=\"$application\"})",
     "legendFormat": "{{http_url}}"
    }
   ]
  },
  {
   "title": "5xx error rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (http_method,http_url)(increase(http_client_requests_count{container=\"$application\",http_status_code=~\"5.*\"}[5m]))/sum by (http_method,http_url)(increase(http_client_requests_count{container=\"$application\"}[5m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx error rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (http_method,http_url)(increase(http_client_requests_count{container=\"$application\",http_status_code=~\"4.*\"}[5m]))/sum by (http_method,http_url)(increase(http_client_requests_count{container=\"$application\"}[5m])) >0",
     "legendFormat": "{{http_method}}:{{http_url}}"
    }
   ]
  },
  {
   "title": "2xx error rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (http_method,http_url)(increase(http_client_requests_count{container=\"$application\",http_status_code=~\"2.*\"}[5m]))/sum by (http_method,http_url)(increase(http_client_requests_count{container=\"$application\"}[5m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}