{
 "title": "Gateway Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "error_status",
    "label": "error_status",
    "query": {
     "query": "http_server_requests_seconds_count{job=\"nc-api-gateway\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request By Error Status",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status) (increase(http_server_requests_seconds_count{job=~\"nc-api-gateway\", uri!~\".*actuator/prometheus\", status=~\"4.*|5.*\"}[5m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5XX by Route ID",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (routeId, httpStatusCode) (increase(spring_cloud_gateway_requests_seconds_count{job=~\"nc-api-gateway\", httpStatusCode=~\"5.*\"}[5m])) > 0",
     "legendFormat": "{{routeId}}_{{httpStatusCode}}"
    }
   ]
  },
  {
   "title": "4XX by Route ID",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum by (routeId, httpStatusCode) (increase(spring_cloud_gateway_requests_seconds_count{job=~\"nc-api-gateway\", httpStatusCode=~\"4.*\"}[5m])) > 0",
     "legendFormat": "{{routeId}}_{{httpStatusCode}}"
    }
   ]
  },
  {
   "title": "$error_status by Route ID",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "repeat": "error_status",
   "targets": [
    {
     "expr": "sum by (routeId, httpStatusCode) (increase(spring_cloud_gateway_requests_seconds_count{job=~\"nc-api-gateway\", httpStatusCode=~\"$error_status\"}[5m])) > 0",
     "legendFormat": "{{routeId}}_{{httpStatusCode}}"
    }
   ]
  }
 ]
}