{
 "title": "K8s Applications",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"integrations/kubernetes/kube-state-metrics\", namespace!~\"kube-.*|cert-.*|ingress.*\"},namespace)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(kube_deployment_status_replicas_available{ namespace=\"$namespace\"},deployment)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{pod=~\"$application.*\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service Health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{container=\"$application\", namespace=\"$namespace\", endpoint!=\"metrics\", instance!~\".*:9094\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{namespace=\"$namespace\", container=~\"$application\"}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{namespace=\"$namespace\", container=\"$application\", uri!=\"/actuator/prometheus\"})"
    }
   ]
  },
  {
   "title": "Requests (Period)",
   "type": "stat",
   "description": "No. of requests in interval",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", job=~\"$application\", pod=~\"$pod\", uri!~\".*actuator.*\"}[$__range]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HTTP 2xx",
   "type": "stat",
   "description": "No. of 2xx requests in the range selected above",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", job=~\"$application\",pod=~\"$pod\", uri!~\".*actuator.*\", status=~\"2..\"}[$__range]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HTTP 4xx",
   "type": "stat",
   "description": "No. of 4xx requests in the range selected above",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", job=\"$application\", pod=~\"$pod\", uri!~\".*actuator.*\", status=~\"4..\"}[$__range]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HTTP 5xx",
   "type": "stat",
   "description": "No. of 5xx requests in the range selected above",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", job= \"$application\", pod=~\"$pod\", uri!~\".*actuator.*\", status=~\"5..\"}[$__range]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{namespace=\"$namespace\", container=\"$application\", outcome=\"SERVER_ERROR\"})"
    }
   ]
  },
  {
   "title": "Pod Request imbalance",
   "type": "gauge",
   "description": "No. of requests in 5 minute range",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(topk(1, sum by (pod,container) (rate(http_server_requests_seconds_count{namespace=\"$namespace\",container=\"$application\", uri!~\"/actuator.*\"}[$__range])))) by (container)\r\n-\r\nsum(bottomk(1, sum by (pod,container) (rate(http_server_requests_seconds_count{namespace=\"$namespace\",container=\"$application\", uri!~\"/actuator.*\"}[$__range])))) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "HTTP Requests By Host",
   "type": "timeseries",
   "description": "No. of requests in 5 minute range",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(http_server_requests_seconds_count{namespace=\"$namespace\",container=\"$application\", uri!~\"/actuator.*\"}[$__range]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "description": "No. of requests in 5 minute range grouped by status code",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_server_requests_seconds_sum{namespace=\"$namespace\", job= \"$application\", pod=~\"$pod\", uri!~\".*actuator.*\"}[5m]) * 60)",
     "legendFormat": "HTTP {{status}} {{host}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "99th, 95th and 50th percentiles",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_bucket{namespace=\"$namespace\",job=~\"$application\", pod=~\"$pod\"}[5m])) by (le)) * 1 ",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{namespace=\"$namespace\",job=~\"$application\", pod=~\"$pod\"}[5m])) by (le)) * 1 ",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_bucket{namespace=\"$namespace\",job=~\"$application\", pod=~\"$pod\"}[5m])) by (le)) * 1 ",
     "legendFormat": "50th Percentile"
    }
   ]
  },
  {
   "title": "HTTP 5xx by Endpoint",
   "type": "timeseries",
   "description": "No. of 5xx requests in the range selected above",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{namespace=\"$namespace\", job= \"$application\", pod=~\"$pod\", uri!~\".*actuator.*\", status=~\"5..\"}[$__range])>0",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "HTTP 4xx by Endpoint",
   "type": "timeseries",
   "description": "No. of 5xx requests in the range selected above",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{namespace=\"$namespace\", job= \"$application\", pod=~\"$pod\", uri!~\".*actuator.*\", status=~\"4..\"}[$__range])>0",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration(TOP 5) ",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by(uri)(http_server_requests_seconds_sum{container=\"$application\"}) / sum by(uri)(http_server_requests_seconds_count{container=\"$application\"}))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  { "title": "System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "CPU Usage by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"$application\", image!=\"\", container!=\"\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$application\", image!=\"\", container!=\"\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Total pod CPU Requests usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"$application\", image!=\"\"}[$__rate_interval])) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"$application\", unit=\"core\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Total pod CPU Limits usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"$application\", image!=\"\"}[$__rate_interval])) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$application\", unit=\"core\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Total pod RAM Requests usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$application\", image!=\"\"}) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"$application\", unit=\"byte\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Total pod RAM Limits usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$application\", image!=\"\"}) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$application\", unit=\"byte\"}) ",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Resources by container",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"$application\", unit=\"core\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$application\", unit=\"core\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"$application\", unit=\"byte\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$application\", unit=\"byte\"}) by (container)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"$application\", image!=\"\", container!=\"\"}[$__rate_interval])) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$application\", image!=\"\", container!=\"\"}) by (container)"
    }
   ]
  },
  { "title": "Outgoing HTTP Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Top 5xx Outgoing Fail",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, increase(http_client_requests_seconds_count{status!~\"2..\", container=\"$application\"}[$__range])>0)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Top Outgoing Success",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, increase(http_client_requests_seconds_count{status=~\"2..\", container=\"$application\"}[$__range])>0)",
     "legendFormat": "{{uri}}"
    }
   ]
  }
 ]
}