{
 "title": "Payment_Gateway_Requests",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Zwitch ext transfer initiate Count metrics",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (vendor) (increase(payment_gateway_requests_total{api=\"external_transfer\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zwitch ext transfer initiate Count metrics",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (vendor) (increase(payment_gateway_requests_total{api=\"external_transfer\", http_status=~\"2.*\"}[$__range]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum by (vendor) (increase(payment_gateway_requests_total{api=\"external_transfer\", http_status=~\"5.*\"}[$__range]))",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum by (vendor) (increase(payment_gateway_requests_total{api=\"external_transfer\", http_status=~\"4.*\"}[$__range]))",
     "legendFormat": "4xx"
    }
   ]
  },
  {
   "title": "Zwitch ext transfer initiate Count metrics",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (vendor) (increase(payment_gateway_requests_total{api=\"external_transfer\", http_status=~\"2.*\"}[$__range]))/(sum by (vendor) (increase(payment_gateway_requests_total{api=\"external_transfer\"}[$__range])))) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "(sum by (vendor) (increase(payment_gateway_requests_total{api=\"external_transfer\", http_status=~\"5.*\"}[$__range]))/(sum by (vendor) (increase(payment_gateway_requests_total{api=\"external_transfer\"}[$__range]))))*100",
     "legendFormat": "5xx"
    },
    {
     "expr": "(sum by (vendor) (increase(payment_gateway_requests_total{api=\"external_transfer\", http_status=~\"4.*\"}[$__range]))/(sum by (vendor) (increase(payment_gateway_requests_total{api=\"external_transfer\"}[$__range]))))*100",
     "legendFormat": "4xx"
    }
   ]
  },
  {
   "title": "Zwitch ext transfer initiate Count metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (vendor) (increase(payment_gateway_requests_total{api=\"external_transfer\", http_status=~\"2.*\"}[$__range]))/(sum by (vendor) (increase(payment_gateway_requests_total{api=\"external_transfer\"}[$__range])))) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "(sum by (vendor) (increase(payment_gateway_requests_total{api=\"external_transfer\", http_status=~\"5.*\"}[$__range]))/(sum by (vendor) (increase(payment_gateway_requests_total{api=\"external_transfer\"}[$__range]))))*100",
     "legendFormat": "5xx"
    },
    {
     "expr": "(sum by (vendor) (increase(payment_gateway_requests_total{api=\"external_transfer\", http_status=~\"4.*\"}[$__range]))/(sum by (vendor) (increase(payment_gateway_requests_total{api=\"external_transfer\"}[$__range]))))*100",
     "legendFormat": "4xx"
    },
    {
     "expr": "(sum by (vendor) ((increase(payment_gateway_requests_total{api=\"external_transfer\"}[$__range])) * 0.1)/(sum by (vendor) (increase(payment_gateway_requests_total{api=\"external_transfer\"}[$__range]))))*100",
     "legendFormat": "Threshold"
    }
   ]
  },
  {
   "title": "Zwitch bank error webhook Count metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(payment_gateway_requests_total{api=\"webhook\",vendor_status!=\"zwch_response_200\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zwitch ext transfer initiate Count metrics",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (vendor) (increase(payment_gateway_requests_total{api=\"external_transfer\", http_status=~\"2.*\"}[$__range]))/(sum by (vendor) (increase(payment_gateway_requests_total{api=\"external_transfer\"}[$__range])))) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "(sum by (vendor) (increase(payment_gateway_requests_total{api=\"external_transfer\", http_status=~\"5.*\"}[$__range]))/(sum by (vendor) (increase(payment_gateway_requests_total{api=\"external_transfer\"}[$__range]))))*100",
     "legendFormat": "5xx"
    },
    {
     "expr": "(sum by (vendor) (increase(payment_gateway_requests_total{api=\"external_transfer\", http_status=~\"4.*\"}[$__range]))/(sum by (vendor) (increase(payment_gateway_requests_total{api=\"external_transfer\"}[$__range]))))*100",
     "legendFormat": "4xx"
    }
   ]
  },
  {
   "title": "Zwitch bank_error webhook error level Count metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(payment_gateway_requests_total{api=\"webhook\",vendor_status!=\"zwch_response_200\"}) by (vendor_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zwitch success webhook Count metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(payment_gateway_requests_total{api=\"webhook\",vendor_status=\"zwch_response_200\"}) by (vendor_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zwitch ext transfer initiation rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(rate(payment_gateway_requests_total{api=\"external_transfer\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zwitch bank_error webhook rate metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum(rate(payment_gateway_requests_total{api=\"webhook\",vendor_status!=\"zwch_response_200\"}[5m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vendor - API metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(rate(payment_gateway_requests_total[5m])) by (api, http_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zwitch bank_error webhook error level rate metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "sum(rate(payment_gateway_requests_total{api=\"webhook\",vendor_status!=\"zwch_response_200\"}[5m])) by (vendor_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vendor - Exception metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum(rate(payment_gateway_requests_total[5m])) by (vendor, exception)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vendor - Status metric",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "sum(rate(payment_gateway_requests_total[5m])) by ( vendor, http_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vendor - Vendor_Status metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sum(rate(payment_gateway_requests_total[5m])) by (vendor, vendor_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vendor - Status metric",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "expr": "sum(increase(payment_gateway_requests_total{api=\"external_transfer\"}[$__range])) by ( vendor, http_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Zwitch Webhook Received",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (vendor) (increase(payment_gateway_requests_total{api=\"webhook\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zwitch webhook not success Count metrics",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (vendor) (increase(payment_gateway_requests_total{api=\"webhook\", vendor_status!=\"zwch_response_200\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zwitch Webhooks success error count",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (vendor) (increase(payment_gateway_requests_total{api=\"webhook\"}[$__range]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (vendor) (increase(payment_gateway_requests_total{api=\"webhook\", vendor_status=\"zwch_response_200\"}[$__range]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum by (vendor) (increase(payment_gateway_requests_total{api=\"webhook\", vendor_status!=\"zwch_response_200\"}[$__range]))",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Zwitch bank_error webhook error level Count metrics",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (vendor_status) (increase(payment_gateway_requests_total{api=\"webhook\", vendor_status!=\"zwch_response_200\"}[$__range])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ext Transfers Initiated IFSC",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (bank_ifsc) (increase(payment_gateway_requests_total{api=\"external_transfer\", bank_ifsc!=\"\", http_status=\"200\"}[$__range])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Webhook IFSC - Error Status",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 93 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (bank_ifsc, vendor_status) (increase(payment_gateway_requests_total{api=\"webhook\", bank_ifsc!=\"YESB\", bank_ifsc!=\"\", vendor_status!=\"zwch_response_200\"}[$__range])) > 0",
     "legendFormat": "{{bank_ifsc}} => {{vendor_status}}"
    }
   ]
  },
  {
   "title": "Webhook IFSC - Status",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 102 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (bank_ifsc, vendor_status) (increase(payment_gateway_requests_total{api=\"webhook\", bank_ifsc!=\"YESB\", bank_ifsc!=\"\"}[$__range])) > 0",
     "legendFormat": "{{bank_ifsc}} => {{vendor_status}}"
    }
   ]
  },
  {
   "title": "Failing Zwitch APIs - VAN",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 111 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (api, http_status) (increase(zwitch_api_metric_total{http_status!=\"200\"}[$__range])) > 0",
     "legendFormat": "{{http_status}}  {{api}}"
    }
   ]
  },
  {
   "title": "Failing Zwitch APIs - Payments",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 120 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (api, http_status) (increase(payment_gateway_requests_total{api!=\"webhook\", http_status!=\"200\"}[$__range])) > 0",
     "legendFormat": "{{http_status}}  {{api}}"
    }
   ]
  },
  {
   "title": "Zwitch APIs Status - VAN",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 129 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (api, http_status) (increase(zwitch_api_metric_total{}[$__range])) > 0",
     "legendFormat": "{{http_status}}  {{api}}"
    }
   ]
  },
  {
   "title": "Zwitch APIs - Payments",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 138 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (api, http_status) (increase(payment_gateway_requests_total{api!=\"webhook\"}[$__range])) > 0",
     "legendFormat": "{{http_status}}  {{api}}"
    }
   ]
  }
 ]
}