{
 "title": "Kafka Overview",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Brokers Online",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by(cluster) (kafka_server_replicamanager_leadercount{cluster=~\"_analytics_prod\"})"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (kafka_controller_kafkacontroller_activecontrollercount)"
    }
   ]
  },
  {
   "title": "Under Min ISR Partitions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (kafka_cluster_partition_underminisr{cluster=\"_analytics_prod\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (kafka_server_replicamanager_underminisrpartitioncount{cluster=\"_analytics_prod\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (kafka_server_replicamanager_underreplicatedpartitions{cluster=\"_analytics_prod\"})"
    }
   ]
  },
  {
   "title": "Topic Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (kafka_controller_kafkacontroller_globaltopiccount{cluster=\"_analytics_prod\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "At Min ISR Partitions Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (kafka_cluster_partition_atminisr{cluster=\"_analytics_prod\"})"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(jvm_gc_collection_seconds_sum{cluster=\"_analytics_prod\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (rate(process_cpu_seconds_total{job=~\"kafka-node-1|kafka-node-2|kafka-node-3\"}[5m])*100) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by(job) (jvm_memory_bytes_used{cluster=\"_analytics_prod\"}) / (1024*1024)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job) (kafka_server_replicamanager_underreplicatedpartitions)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "At Min ISR Partitions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_atminisrpartitioncount",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Partitions Leader Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_leadercount",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Brokers Online",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(kafka_server_kafkaserver_brokerstate)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Under Min ISR Partitions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_underminisrpartitioncount",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Partitions Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_partitioncount",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages In Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(topic) (increase(kafka_server_brokertopicmetrics_messagesin_total{cluster=\"_analytics_prod\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(job) (increase(kafka_server_brokertopicmetrics_bytesin_total{cluster=\"_analytics_prod\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 53 },
   "targets": [
    {
     "expr": "sum by(topic) (increase(kafka_server_brokertopicmetrics_messagesin_total{cluster=\"_analytics_prod\"}[10m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(job) (increase(kafka_server_brokertopicmetrics_bytesout_total{cluster=\"_analytics_prod\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(topic) (increase(kafka_server_brokertopicmetrics_bytesin_total{cluster=\"_analytics_prod\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(topic) (increase(kafka_server_brokertopicmetrics_bytesout_total{cluster=\"_analytics_prod\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}