{
 "title": "Kafka Metrics",
 "description": "Dashboard for metrics jmx_exporter protmetheus",
 "tags": [ "kafka" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Cluster health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Brokers Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(cluster) (kafka_server_kafkaserver_brokerstate{cluster=\"_analytics_prod\"})"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount)"
    }
   ]
  },
  {
   "title": "Total of Topics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (kafka_controller_kafkacontroller_globaltopiccount)"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(job) (kafka_server_replicamanager_partitioncount)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (kafka_controller_kafkacontroller_offlinepartitionscount)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Consumer Lag",
   "type": "timeseries",
   "description": "The difference between the latest offset and the current offset of a consumer.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(consumergroup, topic) (kafka_consumergroup_lag_sum{cluster=\"_analytics_prod\"})",
     "legendFormat": "{{consumergroup}} --Topic {{topic}}"
    }
   ]
  },
  {
   "title": "Partitions Leader and Replica Per Broker",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "(kafka_server_replicamanager_leadercount * 100) / kafka_server_replicamanager_partitioncount",
     "legendFormat": "__auto"
    },
    {
     "expr": "kafka_server_replicamanager_leadercount"
    },
    {
     "expr": "(kafka_cluster_partition_replicascount)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages Per Second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by(cluster) (rate(kafka_server_brokertopicmetrics_messagesin_total[5m]))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 11, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (increase(kafka_server_brokertopicmetrics_messagesin_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sort(sum by(topic) (rate(kafka_server_brokertopicmetrics_messagesin_total{cluster=\"_analytics_prod\"}[5m])))",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "type": "gauge",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
     "repeat": "broker",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (kafka_network_socketserver_networkprocessoravgidlepercent * 100)",
       "legendFormat": "Network processor avg {{instance}}"
      }
     ]
    },
    {
     "title": "Record Send Rate",
     "type": "timeseries",
     "description": "The rate of messages being sent by producers.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by(request) (kafka_network_requestmetrics_localtimems{request=~\"FetchConsumer|Produce\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": " Network Processor Idle Percentage:",
     "type": "timeseries",
     "description": "The percentage of time the network processor threads are idle.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by(job) (kafka_network_socketserver_controlplanenetworkprocessoravgidlepercent{cluster=\"_analytics_prod\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Kafka Network Idle Percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by(job) (kafka_network_processor_idlepercent)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(request) (kafka_network_requestmetrics_totaltimems{request=\"Produce\", quantile=\"0.99\"})",
       "legendFormat": "Total {{request}} 99th"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(request) (kafka_network_requestmetrics_totaltimems{request=\"FetchConsumer\", quantile=\"0.99\"})",
       "legendFormat": "Total {{request}} 99th"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(request) (kafka_network_requestmetrics_totaltimems{request=\"FetchFollower\", quantile=\"0.99\"})",
       "legendFormat": "Total {{request}} 99th"
      }
     ]
    },
    {
     "title": "Produce Latency 99th per Broker",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "avg by(job) (kafka_network_requestmetrics_totaltimems{request=\"Produce\", quantile=\"0.99\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "FetchConsumer Latency 99th per Broker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
     "targets": [
      {
       "expr": "avg by(job) (kafka_network_requestmetrics_totaltimems{request=\"FetchConsumer\", quantile=\"0.99\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "FetchFollow Latency 99th per Broker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by(job) (kafka_network_requestmetrics_totaltimems{request=\"FetchFollower\", quantile=\"0.99\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Bytes In Per Topic",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by(topic) (rate(kafka_server_brokertopicmetrics_bytesin_total[5m]))",
       "legendFormat": "Topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Bytes Out Per Topic",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by(topic) (rate(kafka_server_brokertopicmetrics_bytesout_total[5m]))",
       "legendFormat": "Topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Total Produce Request Rate Per Topic",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(topic) (rate(kafka_server_brokertopicmetrics_totalproducerequests_total[5m]))",
       "legendFormat": "Topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Bytes In / Out Per Broker",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by(job) (rate(kafka_server_brokertopicmetrics_bytesout_total[5m]))",
       "legendFormat": "Bytes Out [{{job}}]"
      },
      {
       "expr": "sum by(job) (rate(kafka_server_brokertopicmetrics_bytesin_total[5m]))",
       "legendFormat": "Bytes In [{{job}}]"
      }
     ]
    },
    {
     "title": "Produce Request Per Broker",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(instance) (rate(kafka_network_requestmetrics_requests_total{request=~\"Produce\"}[5m]))",
       "legendFormat": "Request: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Troubleshooting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Under Replicated Partitions",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(cluster) (kafka_server_replicamanager_underreplicatedpartitions)",
       "legendFormat": "Kafka-cluster"
      }
     ]
    },
    {
     "title": "Under-Reassigned Partitions",
     "type": "timeseries",
     "description": "Partitions that are not correctly reassigned",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "sum by(job) (kafka_controller_controllerstats_listpartitionreassignmentrateandtimems_count)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed Produce Request Per Broker",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(job) (irate(kafka_server_brokertopicmetrics_failedproducerequests_total[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Failed Fetch Request Per Broker",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(job) (irate(kafka_server_brokertopicmetrics_failedfetchrequests_total[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Failed Produce Request Per Topic",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(topic) (irate(kafka_server_brokertopicmetrics_failedproducerequests_total[5m]))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Failed Fetch Request Per Topic",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(topic) (irate(kafka_server_brokertopicmetrics_failedfetchrequests_total[5m]))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "ZooKeeper Disconnects Per Sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by(job) (irate(kafka_server_sessionexpirelistener_zookeeperdisconnects_total[5m]))",
       "legendFormat": "Broker - {{job}}"
      }
     ]
    },
    {
     "title": "ZooKeeper Expires Per Sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by(job) (irate(kafka_server_sessionexpirelistener_zookeeperexpires_total[5m]))",
       "legendFormat": "Broker - {{job}}"
      }
     ]
    },
    {
     "title": "ZooKeeper Request Latency Ms",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by(job) (kafka_server_zookeeperclientmetrics_zookeeperrequestlatencyms)",
       "legendFormat": "Broker: {{job}}"
      }
     ]
    },
    {
     "title": "Isr Shrinks / Isr Expands Per Sec",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(kafka_server_replicamanager_isrshrinks_total[5m]))",
       "legendFormat": "ISR Shrinks Per Sec"
      },
      {
       "expr": "sum(irate(kafka_server_replicamanager_isrexpands_total[5m]))",
       "legendFormat": "ISR Expands Per Sec"
      }
     ]
    },
    {
     "title": "FetchFollower Request Per Broker",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(job) (rate(kafka_network_requestmetrics_requests_total{request=~\"FetchFollower\"}[5m]))",
       "legendFormat": "Request: {{job}}"
      }
     ]
    },
    {
     "title": "FetchConsumer Request Per Broker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(job) (irate(kafka_network_requestmetrics_requests_total{request=\"FetchConsumer\"}[5m]))",
       "legendFormat": "Request: {{job}}"
      }
     ]
    },
    {
     "title": "Number of Requests Waiting in the Fetch Purgatory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(job) (kafka_server_delayedoperationpurgatory_purgatorysize{delayedOperation=\"Fetch\"})",
       "legendFormat": "Broker {{job}}"
      }
     ]
    },
    {
     "title": "Total Fetch Request Per Broker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(job) (irate(kafka_server_brokertopicmetrics_totalfetchrequests_total[5m]))",
       "legendFormat": "Broker: {{job}}"
      }
     ]
    },
    {
     "title": "Log Flush Stats Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by(job) (irate(kafka_log_logflushstats_logflushrateandtimems_count[5m]))",
       "legendFormat": "Broker - {{job}}"
      }
     ]
    },
    {
     "title": "Number of Requests Waiting in the Producer Purgatory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(instance) (kafka_server_delayedoperationpurgatory_purgatorysize{delayedOperation=\"Produce\"})",
       "legendFormat": "Broker {{instance}}"
      }
     ]
    },
    {
     "title": "Leader Election Rate Count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(job) (irate(kafka_controller_controllerstats_leaderelectionrateandtimems_count[5m]))",
       "legendFormat": "Broker - {{job}}"
      }
     ]
    },
    {
     "title": "Partitions Leader Per Broker",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 70 },
     "targets": [
      {
       "expr": "kafka_cluster_partition_replicascount"
      }
     ]
    },
    {
     "title": "Disk Usage Segment Size",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
     "targets": [
      {
       "expr": "sort(sum by(job) (kafka_log_log_size))",
       "legendFormat": "Instance Broker:  {{job}}"
      }
     ]
    },
    {
     "title": "Count Partition per Broker",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 87 },
     "targets": [
      {
       "expr": "sort(sum by(job) (kafka_server_replicamanager_partitioncount))",
       "legendFormat": "Instance Broker: {{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum by(job) (rate(process_cpu_seconds_total{job=~\"kafka-node-1|kafka-node-2|kafka-node-3\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk I/O Utilization",
     "type": "timeseries",
     "description": "Monitor disk read/write rates",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by(cluster) (kafka_log_logflushstats_logflushrateandtimems{cluster=\"_analytics_prod\"})",
       "legendFormat": "Kafka-cluster"
      }
     ]
    },
    {
     "title": "Time spent in GC",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by(job) (sum without(gc) (rate(jvm_gc_collection_seconds_sum{instance=~\"10.110.0.14:7071|10.110.0.15:7071|10.110.0.16:7071\"}[5m])))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JVM Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(job) (sum without(area) (jvm_memory_bytes_used{job=~\"kafka-node-1|kafka-node-2|kafka-node-3\"}))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JVM Threads Current",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by(job) (jvm_threads_current{cluster=\"_analytics_prod\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC activity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "avg by(gc) (rate(jvm_gc_collection_seconds_count{job=~\"kafka-node-1|kafka-node-2|kafka-node-3\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "JVM Memory Usage (Heap & Non-Heap)",
     "type": "timeseries",
     "description": " Heap memory usage and GC activity.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "sum by(area) (jvm_memory_bytes_used{job=~\"kafka-node-1|kafka-node-2|kafka-node-3\"}) / (1024*1024)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}