apiVersion: v1
kind: Pod
metadata:
  name: multi-volume-pod
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - name: html-storage
      mountPath: /usr/share/nginx/html
    - name: config-storage
      mountPath: /etc/nginx/conf.d
    - name: log-storage
      mountPath: /var/log/nginx
    - name: cache-storage
      mountPath: /var/cache/nginx
    - name: secret-storage
      mountPath: /etc/ssl/certs
      readOnly: true
  volumes:
  - name: html-storage
    persistentVolumeClaim:
      claimName: html-pvc
  - name: config-storage
    configMap:
      name: nginx-config
  - name: log-storage
    emptyDir:
      sizeLimit: 1Gi
  - name: cache-storage
    emptyDir:
      medium: Memory
      sizeLimit: 500Mi
  - name: secret-storage
    secret:
      secretName: ssl-certs

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: html-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi