apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: my-job-container
        image: busybox
        command: ["sh", "-c", "echo Hello World && sleep 30"]
      restartPolicy: Never
  backoffLimit: 4