# ClusterIP Service (Default)
apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip-service
  namespace: default
  labels:
    app: nginx
    type: clusterip
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  sessionAffinity: None

---
# NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
  namespace: default
  labels:
    app: nginx
    type: nodeport
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP

---
# LoadBalancer Service
apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer-service
  namespace: default
  labels:
    app: nginx
    type: loadbalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  loadBalancerSourceRanges:
  - 10.0.0.0/8
  - 192.168.0.0/16

---
# ExternalName Service
apiVersion: v1
kind: Service
metadata:
  name: external-database-service
  namespace: default
spec:
  type: ExternalName
  externalName: database.example.com
  ports:
  - port: 5432

---
# Headless Service
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless-service
  namespace: default
  labels:
    app: nginx
    type: headless
spec:
  clusterIP: None
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP

---
# Multi-Port Service
apiVersion: v1
kind: Service
metadata:
  name: multi-port-service
  namespace: default
spec:
  selector:
    app: web-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP

---
# Service with Session Affinity
apiVersion: v1
kind: Service
metadata:
  name: sticky-session-service
  namespace: default
spec:
  selector:
    app: web-app
  ports:
  - port: 80
    targetPort: 8080
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800