{
 "title": "Prometheus 2.22",
 "description": "Overview of metrics from Prometheus 2.0.  \r\nUseful for using prometheus to monitor your prometheus.\r\nRevisions welcome!",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   {
    "name": "job",
    "query": "label_values(prometheus_build_info,job)"
   },
   {
    "name": "instance",
    "query": "label_values(prometheus_build_info,instance)"
   },
   {
    "name": "interval",
    "query": "1h, 3h, 6h, 12h, 1d, 2d, 7d, 30d, 90d, 180d"
   }
  ]
 },
 "panels": [
  {
   "title": "Prometheus statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "description": "Total number of time series in prometheus\n\nThe volume of the current series of the heard block in Prometheus, real-time data, the head block is on the running memory, and the data can be modified",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"$job\", instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "Reload time",
   "type": "stat",
   "description": "Total number of time series in prometheus\n\nThe volume of the current series of the heard block in Prometheus, real-time data, the head block is on the running memory, and the data can be modified",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_config_last_reload_success_timestamp_seconds{job=\"$job\", instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "Head Chunks",
   "type": "stat",
   "description": "The amount of the current chunk of the heard block in Prometheus, real-time data, the head block is on the running memory, and the data can be modified",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_chunks{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "created Chunks",
   "type": "stat",
   "description": "Total number of chunks created in the head",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(prometheus_tsdb_head_chunks_created_total[5m])"
    }
   ]
  },
  {
   "title": "Head Series",
   "type": "stat",
   "description": "Total number of time series in prometheus\n\nThe amount of the current series of the heard block in Prometheus, real-time data, the head block is on the running memory, and the data can be modified\n\nA time series is considered active if Prometheus scraped new data for it recently. Prometheus provides prometheus_tsdb_head_series metric, which shows the number of active time series. Prometheus holds recently added samples for active time series in RAM, so its RAM usage highly depends on the number of active time series. The number of active time series is connected to cardinality via churn rate. See this article on how to estimate RAM usage for Prometheus from the number of active time series and ingestion rate\nfor link (https://www.robustperception.io/how-much-ram-does-prometheus-2-x-need-for-cardinality-and-ingestion)",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "created Series",
   "type": "stat",
   "description": "Total number of series created in the head",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(prometheus_tsdb_head_series_created_total{job=~\"$job\",instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "Remove Series",
   "type": "stat",
   "description": "Total number of series removed in the head",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(prometheus_tsdb_head_series_removed_total{job=~\"$job\",instance=~\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "Target samples",
   "type": "stat",
   "description": "the number of samples the target exposed",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(scrape_samples_scraped)" }
   ]
  },
  {
   "title": "Total samples",
   "type": "stat",
   "description": "Total number of appended samples at proemtheus start to now",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_samples_appended_total{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Failures & errors [times]",
   "type": "table",
   "description": "All non-zero failures and errors",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(increase(net_conntrack_dialer_conn_failed_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "Failed Connections"
    },
    {
     "expr": "sum(increase(prometheus_evaluator_iterations_missed_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "Missed Iterations"
    },
    {
     "expr": "sum(increase(prometheus_evaluator_iterations_skipped_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Skipped Iterations"
    },
    {
     "expr": "sum(increase(prometheus_rule_evaluation_failures_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Evaluation"
    },
    {
     "expr": "sum(increase(prometheus_sd_azure_refresh_failures_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Azure Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_consul_rpc_failures_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Consul RPC"
    },
    {
     "expr": "sum(increase(prometheus_sd_dns_lookup_failures_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "DNS Lookup"
    },
    {
     "expr": "sum(increase(prometheus_sd_ec2_refresh_failures_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "EC2 Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_gce_refresh_failures_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "GCE Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_marathon_refresh_failures_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Marathon Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_openstack_refresh_failures_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Openstack Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_triton_refresh_failures_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Triton Refresh"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_exceeded_sample_limit_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Sample Limit"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_sample_duplicate_timestamp_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Duplicate Timestamp"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_sample_out_of_bounds_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Timestamp Out of Bounds"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_sample_out_of_order_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Sample Out of Order"
    },
    {
     "expr": "sum(increase(prometheus_treecache_zookeeper_failures_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Zookeeper"
    },
    {
     "expr": "sum(increase(prometheus_tsdb_compactions_failed_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "TSDB Compactions"
    },
    {
     "expr": "sum(increase(prometheus_tsdb_head_series_not_found{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Series Not Found"
    },
    {
     "expr": "sum(increase(prometheus_tsdb_reloads_failures_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Reload"
    }
   ]
  },
  {
   "title": "Prometheus Engine [queries/sec]",
   "type": "table",
   "description": "Evaluate the query rate of Prometheus in the last 5 minutes",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "round(irate(prometheus_engine_query_duration_seconds_count{job=\"$job\",instance=\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total targets",
   "type": "stat",
   "description": "Current number of discovered targets",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(up)" }
   ]
  },
  {
   "title": "Alerts be send",
   "type": "stat",
   "description": "Total number of alerts sent",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "prometheus_notifications_sent_total{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Scrape samples / s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(prometheus_tsdb_head_samples_appended_total{job=\"$job\",instance=\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": " Prometheus Engine [query time-consuming]",
   "type": "table",
   "description": "Evaluate the overall response time of Prometheus, reflecting the average query response time in the last 5 minutes",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "irate(prometheus_engine_query_duration_seconds_sum{job=\"$job\",instance=\"$instance\"}[5m])/irate(prometheus_engine_query_duration_seconds_count{job=\"$job\",instance=\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "piechart",
   "description": "This is probably wrong!  Please help.",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_gc_sys_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "GC metadata"
    },
    {
     "expr": "sum(go_memstats_heap_alloc_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "heap in-use"
    },
    {
     "expr": "sum(go_memstats_heap_idle_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "heap idle"
    },
    {
     "expr": "sum(go_memstats_heap_inuse_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "heap in use"
    },
    {
     "expr": "sum(go_memstats_heap_released_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "heap released"
    },
    {
     "expr": "sum(go_memstats_heap_sys_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "heap system"
    },
    {
     "expr": "sum(go_memstats_mspan_inuse_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "mspan in use"
    },
    {
     "expr": "sum(go_memstats_other_sys_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "other sys"
    }
   ]
  },
  {
   "title": "Total GC [Second-rate]",
   "type": "graph",
   "description": "Runtime of garbage collection in the head block\nGC count",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_gc_duration_seconds_count{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(prometheus_tsdb_head_gc_duration_seconds_sum{job=\"$job\",instance=\"$instance\"}[5m]) / irate(prometheus_tsdb_head_gc_duration_seconds_count{job=\"$job\",instance=\"$instance\"}[5m])",
     "legendFormat": "Seconds"
    }
   ]
  },
  {
   "title": "Scrape time",
   "type": "bargauge",
   "description": "Prometheus Scrape Time",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "topk(10,scrape_duration_seconds)"
    }
   ]
  },
  {
   "title": "Series churn",
   "type": "table",
   "description": "An estimate of the churn rate. Series loads into the cache are considered churn rates. But there are chances of false positives (e.g. series that flashes and disappears) and false negatives (e.g. Series hits sample_limit but is still created in the head block), but generally use as-is",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 21 },
   "targets": [
    { "expr": "topk(10,scrape_series_added)" }
   ]
  },
  {
   "title": "send samples",
   "type": "stat",
   "description": "Samples in to remote storage, compare to samples out for queue managers",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "prometheus_remote_storage_samples_in_total{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "discard sample",
   "type": "graph",
   "description": "Total number of samples which were dropped after being read from the WAL before being sent via remote write",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_remote_storage_dropped_samples_total{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Failed to write to queue",
   "type": "graph",
   "description": "Total number of times enqueue has failed because a shards queue was full",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(prometheus_remote_storage_enqueue_retries_total{job=\"$job\",instance=\"$instance\"}[5m])",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Sample sending failed",
   "type": "graph",
   "description": "Total number of samples which failed on send to remote storage, non-recoverable errors",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_failed_samples_total{job=\"$job\",instance=\"$instance\"}[5m])",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Shard Queue Accumulation",
   "type": "graph",
   "description": "The number of samples pending in the queues shards to be sent to the remote storage",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "prometheus_remote_storage_pending_samples{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "receive samples",
   "type": "stat",
   "description": "Total number of samples successfully sent to remote storage",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "prometheus_remote_storage_succeeded_samples_total{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Resend sample",
   "type": "graph",
   "description": "Total number of samples which failed on send to remote storage but were retried because the send error was recoverable\n\n发送到远程存储失败但被重试的样本总数",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_retried_samples_total{job=\"$job\",instance=\"$instance\"}[5m])",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Fragment maximum processing",
   "type": "graph",
   "description": "The capacity of each shard of the queue used for parallel sending to the remote storage\n\n单个分片最大处理能力",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "prometheus_remote_storage_shard_capacity{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "active shard",
   "type": "graph",
   "description": "The number of shards used for parallel sending to the remote storage\n\n并发的分片处理数",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "prometheus_remote_storage_shards{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Sample processing time [last a minute]",
   "type": "graph",
   "description": "Duration of sample batch send calls to the remote storage\n\nProcessing time for shards sent to remote storage",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 39 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(prometheus_remote_storage_sent_batch_duration_seconds_sum{instance=\"$instance\"}[1m])/increase(prometheus_remote_storage_sent_batch_duration_seconds_count{instance=\"$instance\"}[1m])",
     "legendFormat": "Sample processing time"
    }
   ]
  }
 ]
}