{
 "title": "Logs Usage",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Bytes over stream",
   "type": "timeseries",
   "description": "Bytes used by each log stream for the past five minutes",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "bytes_over_time({job=~\".+\"}[5m])"
    }
   ]
  },
  {
   "title": "Log Entries",
   "type": "timeseries",
   "description": "Number of entries for each log stream over a five minute interval",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({job=~\".+\"}[5m])"
    }
   ]
  },
  {
   "title": "greater than 100 log lines",
   "type": "timeseries",
   "description": "Count the number of entries within the last minute and return any job with greater than 100 log lines",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "count_over_time({job=~\".+\"}[1m]) > 100\r\n"
    }
   ]
  },
  {
   "title": "Count over past hour",
   "type": "timeseries",
   "description": "Count of logs ingested over the past hour and specify host, and job",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\".+\"}[1h])) by (host, job)"
    }
   ]
  }
 ]
}