{
 "title": "Loki / Recording Rules",
 "tags": [ "loki" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(loki_build_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(loki_build_info{cluster=~\"$cluster\"}, namespace)"
   },
   { "name": "loki_datasource", "query": "loki" },
   {
    "name": "tenant",
    "query": "query_result(sum by (id) (grafanacloud_logs_instance_info) and sum(label_replace(loki_tenant:active_streams{cluster=\"$cluster\",namespace=\"$namespace\"},\"id\",\"$1\",\"tenant\",\"(.*)\")) by(id))"
   }
  ]
 },
 "panels": [
  {
   "title": "Appenders Not Ready",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(loki_ruler_wal_appender_ready) by (pod, tenant) == 0"
    }
   ]
  },
  {
   "title": "Samples Appended to WAL per Second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 2, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(loki_ruler_wal_samples_appended_total{tenant=~\"${tenant}\"}[$__rate_interval])) by (tenant) > 0",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Series Created per Second",
   "type": "timeseries",
   "description": "Series are unique combinations of labels",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(loki_ruler_wal_storage_created_series_total{tenant=~\"${tenant}\"}[$__rate_interval])) by (tenant) > 0",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Write Behind",
   "type": "timeseries",
   "description": "Difference between highest timestamp appended to WAL and highest timestamp successfully written to remote storage",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "loki_ruler_wal_prometheus_remote_storage_highest_timestamp_in_seconds{tenant=~\"${tenant}\"}\n- on (tenant)\n  (\n    loki_ruler_wal_prometheus_remote_storage_queue_highest_sent_timestamp_seconds{tenant=~\"${tenant}\"}\n    or vector(0)\n  )",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Samples Sent per Second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(loki_ruler_wal_prometheus_remote_storage_samples_total{tenant=~\"${tenant}\"}[$__rate_interval])) by (tenant) > 0",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "WAL Disk Size",
   "type": "timeseries",
   "description": "\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (tenant) (loki_ruler_wal_disk_size{tenant=~\"${tenant}\"})",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Pending Samples",
   "type": "timeseries",
   "description": "Some number of pending samples is expected, but if remote-write is failing this value will remain high",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "max(loki_ruler_wal_prometheus_remote_storage_samples_pending{tenant=~\"${tenant}\"}) by (tenant,pod) > 0",
     "legendFormat": "{{tenant}}"
    }
   ]
  }
 ]
}