{
 "title": "Secret Leaked from Bitbucket Repositories",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "repositories",
    "label": "Yelp Secret Scanned Repositories",
    "query": "SELECT\nrepos.repo\nFROM\nyelp_detect_secrets_repo_detections  as detections\nJOIN \n    repos\nON \ndetections.repo_id=repos.id"
   },
   {
    "name": "secret_type",
    "label": "Secret Type",
    "query": "SELECT distinct(type) FROM yelp_detect_secrets_repo_detections "
   },
   {
    "name": "hashed_secret",
    "label": "Hashed Seecret",
    "query": "SELECT\n  DISTINCT detections.hashed_secret\nFROM\n  yelp_detect_secrets_repo_detections AS detections\nJOIN \n  repos\nON \n  detections.repo_id = repos.id\nWHERE\n(CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? (repos.repo)) ELSE true END)\nAND\n(CASE WHEN jsonb_array_length('${secret_type:json}'::jsonb) <> 0 THEN ('${secret_type:json}'::jsonb ? (detections.type)) ELSE true END)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Repositories Scan",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  COUNT(*)\r\nFROM (\r\n  SELECT DISTINCT\r\n    repos.repo\r\n  FROM\r\n    repos\r\n\r\n) AS subquery;\r\n"
    }
   ]
  },
  {
   "title": "Total Repositories Secret Found on",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  COUNT(*)\r\nFROM (\r\n  SELECT DISTINCT\r\n    repos.repo\r\n  FROM\r\n    yelp_detect_secrets_repo_detections AS detections\r\n  JOIN \r\n    repos\r\n  ON \r\n    detections.repo_id = repos.id\r\n) AS subquery;\r\n"
    }
   ]
  },
  {
   "title": "Total Secret Detected In All Repo",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from yelp_detect_secrets_repo_detections"
    }
   ]
  },
  {
   "title": "Selected Repo Total Secret Detected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(*)\r\nFROM\r\n  yelp_detect_secrets_repo_detections AS detections\r\nJOIN \r\n  repos\r\nON \r\n  detections.repo_id = repos.id\r\nWHERE \r\n(CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? (repos.repo)) ELSE true END)\r\nAND\r\n(CASE WHEN jsonb_array_length('${secret_type:json}'::jsonb) <> 0 THEN ('${secret_type:json}'::jsonb ? (detections.type)) ELSE true END)\r\nAND\r\n(CASE WHEN jsonb_array_length('${hashed_secret:json}'::jsonb) <> 0 THEN ('${hashed_secret:json}'::jsonb ? (detections.hashed_secret)) ELSE true END)"
    }
   ]
  },
  {
   "title": "Total Unique Secret Hashed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  COUNT(*)\r\nFROM (\r\n  SELECT DISTINCT\r\n    detections.hashed_secret\r\n  FROM\r\n    yelp_detect_secrets_repo_detections AS detections\r\n  JOIN \r\n    repos\r\n  ON \r\n    detections.repo_id = repos.id\r\n  WHERE\r\n    (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? (repos.repo)) ELSE true END)\r\n    AND\r\n    (CASE WHEN jsonb_array_length('${secret_type:json}'::jsonb) <> 0 THEN ('${secret_type:json}'::jsonb ? (detections.type)) ELSE true END)\r\n) AS subquery;\r\n"
    }
   ]
  },
  {
   "title": "Potential Detected Leaked Secrets in the Repos",
   "type": "table",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  detections.type as Type,\r\n  REPLACE(detections.filename, '/mergestat/repo/', '') AS FileName,\r\n  CONCAT(REPLACE(repos.repo, '.git', '/src/main/'), REPLACE(detections.filename, '/mergestat/repo/', ''), '#line-', detections.line_number) AS Link,\r\n  detections.hashed_secret\r\nFROM\r\n  yelp_detect_secrets_repo_detections AS detections\r\nJOIN \r\n  repos\r\nON \r\n  detections.repo_id = repos.id\r\nWHERE \r\n(CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? (repos.repo)) ELSE true END)\r\nAND\r\n(CASE WHEN jsonb_array_length('${secret_type:json}'::jsonb) <> 0 THEN ('${secret_type:json}'::jsonb ? (detections.type)) ELSE true END)\r\nAND\r\n(CASE WHEN jsonb_array_length('${hashed_secret:json}'::jsonb) <> 0 THEN ('${hashed_secret:json}'::jsonb ? (detections.hashed_secret)) ELSE true END)\r\n"
    }
   ]
  }
 ]
}