{
 "title": "Security Report (Log)",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Unauthorized Access Attempts",
   "type": "logs",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=~\"platform|trader-platform|loans|user-growth|fintech\"} |~ \"401 Unauthorized|403 Forbidden|Failed password|Login incorrect|authentication failure\""
    }
   ]
  },
  {
   "title": "Potential SQL Injection Attempts",
   "type": "logs",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=~\"platform|trader-platform|loans|user-growth|fintech\"}|~ \"SQLIntegrityConstraintViolationException|SQLDataException|SQLSyntaxErrorException\""
    }
   ]
  },
  {
   "title": "Access and CSRF-Related Security Exceptions",
   "type": "logs",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=~\"platform|trader-platform|loans|user-growth|fintech\"} |~ `AccessDeniedException|CsrfException|InvalidCsrfTokenException|MissingCsrfTokenException|CookieTheftException|InvalidCookieException|RequestRejectedException`"
    }
   ]
  },
  {
   "title": "Potential Malicious Request Attempted",
   "type": "logs",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{app=\"ingress-nginx\"} \r\n|~ \"(GET|POST|HEAD|OPTIONS|PUT|DELETE|TRACE|CONNECT)\"\r\n|~ \"(?:sqlmap|nmap|dirbuster|nikto|commix|wpscan|fimap|metasploit|curl|wget|python)\""
    }
   ]
  },
  {
   "title": "Python SQL Exception",
   "type": "logs",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "{app=~\"matrix-synapse|bnpl-.*\" } |~ `DataError|IntegrityError|ProgrammingError|OperationalError`\r\n"
    }
   ]
  },
  {
   "title": "Node.js Child Process Detected",
   "type": "logs",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "{namespace=~\"gtp\"} |~ \"node:child_process|spawned process\""
    }
   ]
  },
  {
   "title": "Abnormally Application Terminated/Crashed",
   "type": "logs",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{app=\"ingress-nginx\"} |= `exited on signal 6 (core dumped)`"
    }
   ]
  },
  {
   "title": "Monitoring Spring Expression Exceptions",
   "type": "logs",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "{namespace=~\"platform|trader-platform|loans|user-growth|fintech\"} |~ `ExpressionException`\r\n"
    }
   ]
  }
 ]
}